---
title: "tabooTransactions_s1b_preprocess"
author: "Dean"
output: html_document
---

```{r setup, include=FALSE}
#load packages
library(tidyverse)

#read in de-identified csv file
df_s2_raw <- read.csv("~/Google Drive/My Drive/taboo transactions/OSF materials/manuscript/data/df_s2_raw.csv")
```

remove ineligible participants

```{r}
#keep only those who finished
df_s2 <- df_s2_raw %>% 
  filter(Finished == 1) %>% 
  filter(Progress == 100)
```

Put NA's where necessary

```{r}
df_s2 <- df_s2 %>% 
  mutate(race = ifelse(race == "Click to write Choice 7",NA,race),
         income = ifelse(income == "Prefer not to answer",NA,income))
```

define income and edu as factors

```{r}
df_s2 <- df_s2 %>% 
  mutate(income = factor(income,c("$0-$20,000",
                                  "$20,001-$40,000",
                                  "$40,001-$60,000",
                                  "$60,001-$80,000",
                                  "$80,001-$100,000",
                                  "$100,001-$120,000",
                                  "$120,001-$140,000",
                                  "$140,001-$160,000",
                                  "$160,001-$180,000",
                                  "$180,001-$200,000",
                                  "Over $200,000")),
         edu = factor(edu,c("GED",
                            "2yearColl",
                            "4yearColl",
                            "MA",
                            "PHD")))
```

when more than one race -> change to multiracial

```{r}
df_s2 <- df_s2 %>% 
  separate(race,into = c("race1","race2","race3","race4"),sep = ",") %>% 
  mutate(race = ifelse(is.na(race2),race1,"multiracial")) %>% 
  select(-c(race1,race2,race3,race4))
```

create person benefit scores

```{r}
df_s2 <- df_s2 %>% 
  rowwise() %>% 
  mutate(benefit_short_A = mean(c(phone_short_A,
                                  chem_short_A,
                                  kdny_short_A,
                                  prod_short_A,
                                  appt_short_A)),
         benefit_long_A = mean(c(phone_long_A,
                                 chem_long_A,
                                 kdny_long_A,
                                 prod_long_A,
                                 appt_long_A)),
         benefit_short_B = mean(c(phone_short_B,
                                  chem_short_B,
                                  kdny_short_B,
                                  prod_short_B,
                                  appt_short_B)),
         benefit_long_B = mean(c(phone_long_B,
                                 chem_long_B,
                                 kdny_long_B,
                                 prod_long_B,
                                 appt_long_B)),
         benefit_A = mean(c(phone_short_A,
                            chem_short_A,
                            kdny_short_A,
                            prod_short_A,
                            appt_short_A,
                            phone_long_A,
                            chem_long_A,
                            kdny_long_A,
                            prod_long_A,
                            appt_long_A)),
         benefit_B = mean(c(phone_short_B,
                            chem_short_B,
                            kdny_short_B,
                            prod_short_B,
                            appt_short_B,
                            phone_long_B,
                            chem_long_B,
                            kdny_long_B,
                            prod_long_B,
                            appt_long_B))) %>% 
  ungroup() 
```

take only relevant vars and order in a way that makes sense

```{r}
df_s2 <- df_s2 %>% 
  select(PID,
         benefit_short_A:benefit_B,
         phone_short_A:appt_long_B,
         ideo_gen:ideo_econ,
         SES,
         gender:race,
         feedback)
```

write csv

```{r}
write.csv(df_s2,"~/Google Drive/My Drive/taboo transactions/OSF materials/manuscript/data/df_s2.csv",row.names = F)
```

